name = input ("What is your name? ")
age = input ("What is your age? ")
age = int(age)
city = input ("What is your city? ")
print("My name is " + name )
print("My age is " + str(age))
print("I live in " + city)
print(type(name))
print(type(age))
print(type(city))